/**
 * A live board on a Docs page (`::board`, and each board of a `:::compare`):
 * its command read by the CLI's code, its board generated by the docs' queue
 * when its frame comes near the view, and `<arrowz-board>` mounted only while
 * it is near. The frame takes the board's proportions, margin included,
 * before the board exists, so the page does not move under the reader.
 *
 * The board looks as its command says (`View` from the flags), not as the lab
 * is set; it pans and zooms and does not play. Under it: the label, the
 * report rows the directive names, and the command with Copy.
 */
import { boardViewOf } from '@arrowz/board-element'
import { COMMAND_PREFIX } from '@arrowz/engine/command'
import { reportRows, type StatKey } from '@arrowz/engine/report'
import type { PhrasingContent } from 'mdast'
import type { ContainerDirective } from 'mdast-util-directive'
import { type CSSProperties, type ReactElement, useEffect, useMemo, useRef, useState } from 'react'
import { useDictionary } from '../i18n'
import { CommandText } from '../run/CommandText'
import { useCopy } from '../run/useCopy'
import { BoardCanvas } from '../stage/BoardCanvas'
import { useStore } from '../state/store'
import { aboutOf, type DocsBoardSpec, readBoardCmd, statKeysOf } from './boards'
import { useDocsBoards } from './DocsBoards'
import type { DocsJob, DocsRun } from './docsQueue'
import { Inline } from './Inline'
import { plainText } from './markdown'
import { useNear } from './useNear'

export interface DocsBoardProps {
  readonly label: readonly PhrasingContent[]
  readonly cmd: string
  readonly stats: readonly StatKey[]
  /** The seconds a `manual` board's button promises; null for a board that generates by itself. */
  readonly about: number | null
}

export function DocsBoard({ cmd, ...rest }: DocsBoardProps): ReactElement | null {
  const spec = useMemo(() => readBoardCmd(cmd).spec, [cmd])
  // The content guard refuses a command that does not parse; nothing is drawn for one.
  return spec === null ? null : <LiveBoard spec={spec} {...rest} />
}

export function DocsCompare({ node }: { node: ContainerDirective }): ReactElement {
  const stats = statKeysOf(node.attributes?.['stats'])
  return (
    <div className="fw-docs-compare">
      {node.children.map((child, i) =>
        child.type === 'leafDirective' && child.name === 'board' ? (
          <DocsBoard
            key={i}
            label={child.children}
            cmd={child.attributes?.['cmd'] ?? ''}
            stats={stats}
            about={aboutOf(child.attributes)}
          />
        ) : null,
      )}
    </div>
  )
}

function LiveBoard({
  spec,
  label,
  stats,
  about,
  still = false,
}: Omit<DocsBoardProps, 'cmd'> & { spec: DocsBoardSpec; still?: boolean }): ReactElement {
  const dict = useDictionary()
  const { queue, root } = useDocsBoards()
  const frame = useRef<HTMLDivElement>(null)
  const near = useNear(frame, root)
  const [asked, setAsked] = useState(about === null)
  const [attempt, setAttempt] = useState(0)
  const [job, setJob] = useState<DocsJob>(() => {
    const hit = queue.cached(spec.key)
    return hit === undefined ? { state: 'waiting' } : { state: 'done', run: hit }
  })
  useEffect(() => {
    if (!near || !asked) return
    return queue.request(spec.key, spec.params, setJob)
  }, [near, asked, attempt, queue, spec])
  const run = job.state === 'done' ? job.run : null
  const { W, H } = spec.params
  const pad = spec.view.pad
  const ratio = (W + 2 * pad) / (H + 2 * pad)
  const name = plainText(label)
  return (
    <figure className="fw-docs-board" aria-label={name}>
      <div
        ref={frame}
        className="fw-docs-frame"
        style={{ aspectRatio: `${W + 2 * pad} / ${H + 2 * pad}`, '--ar': String(ratio) } as CSSProperties}
      >
        {near && run !== null ? (
          <BoardView run={run} spec={spec} still={still} />
        ) : !asked ? (
          <button type="button" className="fw-btn" onClick={() => setAsked(true)}>
            {dict.t('docsBoardGenerate', about ?? 0)}
          </button>
        ) : job.state === 'failed' ? (
          <div className="fw-docs-wait">
            <p role="alert">{dict.t('docsBoardFailed', job.message)}</p>
            <button type="button" className="fw-btn" onClick={() => setAttempt((n) => n + 1)}>
              {dict.t('docsBoardTryAgain')}
            </button>
          </div>
        ) : near ? (
          <span className="fw-docs-wait">{dict.t('generating')}</span>
        ) : null}
      </div>
      <figcaption>
        <Inline nodes={label} />
      </figcaption>
      {stats.length > 0 ? <Stats keys={stats} run={run} /> : null}
      {run !== null && !run.report.ok ? <p className="fw-docs-boardnote">{dict.t('notClosedShort')}</p> : null}
      <BoardCommand spec={spec} name={name} />
    </figure>
  )
}

/** The element for a finished board, under the command's look; exported for the still-board test. */
export function BoardView({ run, spec, still }: { run: DocsRun; spec: DocsBoardSpec; still: boolean }): ReactElement {
  const lang = useStore((state) => state.lang.lang)
  const view = spec.view
  // Colours only where the command states them: an empty field would beat the theme (see `BoardFrame`).
  const elementView = useMemo(
    () => ({
      ...boardViewOf(view, !run.report.ok),
      ...(view.palette.length > 0 ? { palette: view.palette } : {}),
      ...(view.paper === '' ? {} : { paper: view.paper }),
      ...(view.ink === '' ? {} : { ink: view.ink }),
      ...(view.highlight === '' ? {} : { highlight: view.highlight }),
    }),
    [view, run],
  )
  return (
    <BoardCanvas
      className={still ? 'still' : undefined}
      board={run.board}
      view={elementView}
      lang={lang}
      enableColors
      theme={view.theme}
      showPoints={view.showPoints}
      pointColor={view.pointColor}
      pointRadius={view.pointRadius}
      pad={view.pad}
    >
      {/* An empty bar in the controls slot: a still board shows no buttons it could not take. */}
      {still ? <span slot="controls" /> : null}
    </BoardCanvas>
  )
}

function Stats({ keys, run }: { keys: readonly StatKey[]; run: DocsRun | null }): ReactElement {
  const dict = useDictionary()
  const rows = run === null ? [] : reportRows(run.report, run.params, dict)
  return (
    <dl className="fw-docs-stats">
      {keys.map((key) => {
        const row = rows.find((r) => r.key === key)
        const value =
          row === undefined
            ? '—'
            : key === 'time'
              ? dict.t('statSumSeconds', ((row.num ?? 0) / 1000).toFixed(2))
              : row.value
        return (
          <div key={key}>
            <dt>{row?.label ?? dict.t(`stat_${key}` as const)}</dt>
            <dd>{value}</dd>
          </div>
        )
      })}
    </dl>
  )
}

function BoardCommand({ spec, name }: { spec: DocsBoardSpec; name: string }): ReactElement {
  const dict = useDictionary()
  const { copied, copy } = useCopy()
  const command = `${COMMAND_PREFIX} ${spec.cmd}`
  return (
    <div className="fw-docs-boardcmd">
      <pre className="fw-cmd">
        <CommandText command={command} />
      </pre>
      <div className="fw-docs-boardacts">
        <button
          type="button"
          className="fw-btn"
          aria-label={dict.t('docsBoardCopy', name)}
          onClick={() => copy(command)}
        >
          {copied ? dict.t('copied') : dict.t('copy')}
        </button>
      </div>
    </div>
  )
}
